### ISSUE TITLE
nvim does not support the (expr1 ?? expr2) syntax

### ISSUE THREAD

**Issue by clarkwang** [habamax/vim-habamax#3]
https://github.com/habamax/vim-habamax/blob/ebb70a0077ed30f911a2efac07cb5289c67a41a2/colors/habamax.vim#L15

Could we change it to `?:` so it'll be compatible with nvim?

**Comment by craigmac** [comment]
this is changed in the shipped version with nvim runtime, no need to fix it here for neovim

**Comment by clarkwang** [comment]
OK. I did not know it's already part of nvim.
