### ISSUE TITLE
Invalid Expression ? 0 ) : -1 on nvim-qt

### ISSUE THREAD

**Issue by marciovmf** [habamax/vim-habamax#4]
Hey there,
This ternary check on line 15 `let s:t_Co = exists('&t_Co') && !has('gui_running') ? (&t_Co ?? 0) : -1`  raises some errors on _nvim-qt v0.2.17.0_
![image](https://github.com/habamax/vim-habamax/assets/25437129/ed4739a7-0e26-4a92-96cb-f3d0139d477c)

Just rewriting it with normal if/else seems to be enough to load it without issues.
```
let s:t_Co = -1

if exists('&t_Co') && !has('gui_running')
    if !empty(&t_Co)
        let s:t_Co = &t_Co
    else
        let s:t_Co = 0
    endif
endif
```

**Comment by shantanoo-desai** [comment]
This error persists when using it also in `vim 8.1` too.

**Comment by w4term3loon** [comment]
Created a pull for the fix: https://github.com/habamax/vim-habamax/pull/5

**Comment by habamax** [comment]
Colorscheme is included both into vim and neovim quite a time ago, not sure if we need to fix it here.

https://github.com/neovim/neovim/blob/a7550a20e0c3084eacd2b4ede1e6a94f282c2fb8/runtime/colors/habamax.vim#L17-L25
